const ActionType = {
  FETCH_ALL_TASKS_ING: 1,
  FETCH_ALL_TASKS_DONE: 2,
  FETCH_ALL_TASKS_ERROR: 3,
  CREATE_TASK_ING: 4,
  CREATE_TASK_DONE: 5,
  CREATE_TASK_ERROR: 6,
  DELETE_TASK: 7,
  UPDATE_STORAGE_INFO: 8,
  UPDATE_CONNECTION_STATUS: 9,
  FETCH_SUBTASK_ING: 10,
  FETACH_SUBTASK_DNOE: 11,
  FETCH_SUBTASK_ERROR: 12,
  CLEAR_SUBTASK: 13,
};
export default ActionType;
